version: '2'
services:
    jhipsterapplication-app:
        image: jhipsterapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterapplication-postgresql:5432/jhipsterApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterapplication-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterapplication-postgresql
